config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :home, only: [:index]
  resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
  resources :expenses, only: [:new, :create, :edit, :update, :edit, :update, :destroy]
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :manage, Group, author_id: user.id
    can :manage, Expense, author_id: user.id
    can :manage, GroupExpense
    return unless user.admin?

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :expense, dependent: :destroy
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :expenses

  validates :name, presence: true, format: { with: /[a-zA-Z]/ }
  validates :role, presence: true, format: { with: /[a-zA-Z]/ }
  validates :email, presence: true, format: { with: Devise.email_regexp }

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || groups_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource
  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new
    @expense.name = params[:name]
    @expense.amount = params[:amount]
    @expense.author = current_user
    if @expense.save!
      @group_expense = GroupExpense.new
      @group_expense.group_id = params[:group_id]
      @group_expense.expense_id = @expense.id
      if @group_expense.save!
        redirect_to group_path(id: params[:group_id]), notice: 'New expense created'
      else
        :new
      end
    else
      :new
    end
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])
    @expense.name = params[:expense][:name]
    @expense.amount = params[:expense][:amount]
    if @expense.save!
      redirect_to group_path(id: params[:group_id]), notice: 'Category Updated'
    else
      render 'update'
    end
  end

  def destroy
    group_expense = GroupExpense.find_by(group_id: params[:group_id], expense_id: params[:id])
    redirect_to group_path(id: params[:group_id]) if group_expense.destroy
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  def index
    @groups = Group.where(author_id: current_user).order(created_at: :desc)
    @total_arr = []
    @groups.each do |group|
      @expenses = Expense.joins(:group_expenses,
                                :groups).where(group_expenses: { group_id: group.id }).group(:amount).sum(:amount)
      @total_arr << @expenses.values.sum
    end
  end

  def show
    @expenses = []
    @group_expenses = GroupExpense.where(group_id: params[:id]).order(created_at: :desc)
    @total = 0
    @group_expenses.each do |element|
      @expense = Expense.find(element.expense_id)
      @total += @expense.amount
      @expenses << @expense
    end
  end

  def new
    Group.new
  end

  def create
    @group = Group.new
    @group.name = params[:name]
    @group.icon = params[:icon]
    @group.author = current_user
    if @group.save!
      redirect_to groups_path, notice: 'New category created'
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.name = params[:group][:name]
    @group.icon = params[:group][:icon]
    if @group.save!
      redirect_to groups_path, notice: 'Category Updated'
    else
      render 'update'
    end
  end

  def destroy
    group = Group.find(params[:id])
    redirect_to groups_path if Group.destroy(group.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/edit.html.erb
<div class="header-container">
<%=link_to "<", group_path(params[:group_id])%>
<h2>CREATE NEW EXPENSE</h2>
<p></p>
</div>
<%= form_with model: @expense, url:group_expense_path(group_id: params[:group_id], id: @expense.id), class:"new-form", method: :patch do |form| %> 
  <%= form.label :name, "Name" %>
  <%= form.text_field :name, class:"input"  %>
  <%= form.label :amount, "Amount $" %>
  <%= form.number_field :amount, step: :any, class:"input" %>
  <div class="create-btn">
      <%= form.submit "UPDATE" %>
  </div>
<% end %>

app/views/expenses/new.html.erb
<div class="header-container">
<%=link_to "<", group_path(params[:group_id])%>
<h2>CREATE NEW EXPENSE</h2>
<p></p>
</div>
<%= form_with url:group_expenses_path(group_id: params[:group_id]), class:"new-form" do |form| %> 
  <%= form.label :name, "Name" %>
  <%= form.text_field :name, class:"input"  %>
  <%= form.label :amount, "Amount $" %>
  <%= form.number_field :amount, step: :any, class:"input" %>
  <div class="create-btn">
      <%= form.submit "CREATE" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="header-container">
<p><%=link_to "<", groups_path%></p>
<h2>UPDATE CATEGORY</h2>
<p></p>
</div>
<%= form_with model: @group, url:group_path(params[:id]), class:"new-form", method: :patch do |form| %>
  <%= form.label :name, "Name" %>
  <%= form.text_field :name, class:"input"  %>
  <%= form.label :icon, "Icon (URL)" %>
  <%= form.text_field :icon, class:"input" %>
  <div class="create-btn">
      <%= form.submit "Update"%>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="header-container">
<p><%=current_user.name%></p> 
<h2 class=title-categories>CATEGORIES</h2>
 <% if current_user.present? %>
      <%=button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }%> 
      <% end %>
</div>
<div class="categories-container">
<% @groups.each_with_index do |group,index|%>
    <div class="category">
    <div class="category-button-box">
        <%=button_to "Update", edit_group_path(group.id), method: :get %>
        <%=button_to "Delete", group_path(group.id), method: :delete %>
    </div>
    <%=link_to group_path(id: group.id) do%>
        <img src=<%=group.icon%> alt="Category image"> 
        <div class="group-info">
        <p><%=group.name%></p> 
        <p>$<%=@total_arr[index]%></p>
        </div>
    </div>
    <%end%> 
<%end%>
</div>
<div class="new-btn">
<%if can? :manage, Group %>
<%=link_to "ADD CATEGORY", new_group_path%> 
<%end%>
</div>

app/views/groups/new.html.erb
<div class="header-container">
<p><%=link_to "<", groups_path%></p>
<h2>CREATE NEW CATEGORY</h2>
<p></p>
</div>
<%= form_with url:groups_path, class:"new-form" do |form| %>
  <%= form.label :name, "Name" %>
  <%= form.text_field :name, class:"input"  %>
  <%= form.label :icon, "Icon (URL)" %>
  <%= form.text_field :icon, class:"input" %>
  <div class="create-btn">
  <%= form.submit "CREATE"%>
  </div>
<% end %>

app/views/groups/show.html.erb
<div class="header-container">
<%=link_to "<", groups_path%>
<h2>EXPENSES</h2>
<p></p>
</div>
<p class="total">Total: $<%=@total%></p>
<div class="expenses-container">
<% @expenses.each do |expense|%>    
    <div class="expense">
        <div class="expense-button-box">
        <%=button_to "Update", edit_group_expense_path(group_id: params[:id], id: expense.id ), method: :get %>
        <%=button_to "Delete", group_expense_path(group_id: params[:id], id: expense.id ), method: :delete %>
        </div>
        <div class="expense-info">
        <p><%=expense.name%></p>
        <p>$<%=expense.amount%></p>
        </div>
    </div>
<%end%>
</div>
<div class="new-btn">
<%if can? :manage, Expense%>
<%=link_to "ADD EXPENSE", new_group_expense_path(group_id: params[:id]) %>
<%end%>
</div>

app/views/home/index.html.erb
<%=image_tag("budget_calculator.png", class: "splash-img")%>
<div class="sign-links">
    <%=link_to "SIGN UP", new_user_registration_path, class:"sign-up-link" %>
    <%=link_to "LOG IN", new_user_session_path, class:"sign-in-link"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta property="og:title" content="Budget Calculator" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="https://user-images.githubusercontent.com/98363075/189417331-02a86e54-4800-4f07-9ebf-3452aaaa7cac.png"/>
    <meta property="og:url" content="https://santiago-budget-calculator.herokuapp.com/" />
    <meta
      name="description"
      content="This app is a mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what."/>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>